### ISSUE TITLE
view呈现问题,请教

### ISSUE THREAD

**Issue by jesse920524** [dinuscxj/LoadingDrawable#10]
当我打开一个Activity时,我想要先显示loading动画,后台线程执行网络请求逻辑
当请求结束时,loading动画消失,显示正常的layout.
请问如何实现这样的效果?

目前我的方案是使用自定义ProgressDialog,
或许还可以通过FrameLayout嵌套progressBar和其他view,通过visibility属性来控制.
是否存在更好的解决方案?
新手问题,见笑了.

**Comment by dinuscxj** [comment]
@jesse920524 你使用LoadingView就可以，也可以根据LoadingView改造成为自己需要的组件
