### ISSUE TITLE
Can I add this view to my activity programatically?

### ISSUE THREAD

**Issue by wonsuc** [dinuscxj/LoadingDrawable#14]
public void showLoadingDialog(String message) {
        dismissDialog();

        if (mProgressDialog == null) {
            mProgressDialog = new ProgressDialog(this);
            mProgressDialog.setIndeterminate(true);
            mProgressDialog.setTitle("");
        }

        mProgressDialog.setMessage(message);
        mProgressDialog.show();
    }

Like standard android ProgressDialog as above code.
Thanks.

**Comment by dinuscxj** [comment]
Yes. you can try LoadingView

**Comment by wonsuc** [comment]
But how to implement it?
I tried to create new instance of LoadingView and add it to activity's content view. But nothing works. Any demo or example?

**Comment by wonsuc** [comment]
Oh ok I solved it thanks!
