### ISSUE TITLE
 analysis the Fish Animator

### ISSUE THREAD

**Issue by xsfelvis** [dinuscxj/LoadingDrawable#5]
3q for your wonderful code,I spend some spare time  in analysising the Fish Animator。As a newcomer in Android，I hope I did not make mistakes in my blog。[http://blog.csdn.net/XSF50717/article/details/51494266](url)，Waiting for your suggestion。

**Comment by dinuscxj** [comment]
@xsfelvis  great.  besides I will add the blog url to the project

**Comment by xsfelvis** [comment]
my great honor！
