### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by rogerou** [dinuscxj/LoadingDrawable#9]
<code>
 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
</code>

在调用BalloonLoadingRenderer 的时候直接会空指针，而且还有我在Recycleview 配合Glide PlaceHolder调用的时候 只能显示静止的 不会动。

**Comment by rogerou** [comment]
<code>
android.view.GLES20Canvas.drawText(GLES20Canvas.java:918) 
at app.dinus.com.loadingdrawable.render.goods.BalloonLoadingRenderer.draw(BalloonLoadingRenderer.java:141)
  at app.dinus.com.loadingdrawable.LoadingDrawable.draw(LoadingDrawable.java:38)
</code>

**Comment by dinuscxj** [comment]
@rogerou 你重现拉一下代码，我做了一下调整

**Comment by dinuscxj** [comment]
@rogerou 你的不绘制动画，应该没有调用LoadingRenderer的start方法吧

**Comment by rogerou** [comment]
@dinuscxj  sorry，一时心急就没看Example 的确是这个问题

**Comment by dinuscxj** [comment]
@rogerou 引入了LoadingView 使用上更加简单了

**Comment by rogerou** [comment]
@dinuscxj 很棒
